---
- name: Install Certbot and obtain SSL certificates
  hosts: remote_servers
  become: yes
  vars_files:
    - vars.yml
  tasks:
    - name: Install Certbot (Debian/Ubuntu)
      apt:
        name: certbot
        state: present
      when: ansible_os_family == 'Debian'

    - name: Install Certbot (RHEL/CentOS)
      yum:
        name: certbot
        state: present
      when: ansible_os_family == 'RedHat'

    - name: Obtain SSL certificates using Certbot
      shell: "certbot certonly --non-interactive --agree-tos --email {{ certbot_email }} --webroot -w {{ certbot_webroot_path }} {% for domain in certbot_domains %}-d {{ domain }} {% endfor %}"
