---
- name: Install AWS CLI
  hosts: remote_servers
  become: yes 

  tasks:
    - name: Install pip (Python package manager)
      
      package:
        name: python3-pip
        state: present
      
      tags: ['pip']

    - name: Install AWS CLI using pip
      pip:
        name: awscli
        state: present
